name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! Thank you for your first contribution to our project. :)'
        pr-message: 'Hi! Thank you for your first PR to our project. You are helping to make our product better! :)'